
/*------------------------------------------------------------------------
    File        : EnumHeader1
    Purpose     : Purpose of EnumHeader1
    Syntax      : Syntax of EnumHeader1
    Description : Description of EnumHeader1
    Author(s)   : Han Solo
    Created     : Tue Dec 31 17:46:24 CET 2019
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM header.EnumHeader1 FLAGS :  

    /* 
    Enum List 
    */
    DEFINE ENUM HanSolo = 1
                LukeSkywalker = 2.

END ENUM.