
/*------------------------------------------------------------------------
    File        : ITruc
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : cbr
    Created     : Mon Dec 02 19:29:21 CET 2019
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE Hello.ITruc:  
  
    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    METHOD PUBLIC CHARACTER getFamily(  ).

END INTERFACE.
